sudo: required
language: bash
services:
  - docker

before_install:
  - docker build -t libstorage-ng-image .
script:
  # the "storage-ng-travis-cpp" script is included in the base yastdevel/storage-ng image
  # see https://github.com/yast/docker-storage-ng/blob/master/storage-ng-travis-cpp
  - /bin/bash .travis_script.sh
